import { createElement } from 'lwc';
import WireGetFieldAndFieldDisplayValues from 'c/wireGetFieldAndFieldDisplayValues';

describe('c-wire-get-field-and-field-display-values', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-wire-get-field-and-field-display-values', {
            is: WireGetFieldAndFieldDisplayValues
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});